name: Build Frontend & Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install and build Backend
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Build Backend
        run: |
          cd backend
          npm run build || echo "No build step, skipping..."

      # Install and build Frontend
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
