name: Backend Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run backend server in the background
        run: |
          cd backend
          nohup node server.js > server.log 2>&1 &

      - name: Wait for server to start
        run: sleep 5

      - name: Check if `/products` API is working
        run: curl -f http://localhost:3000/products || (echo "API check failed" && exit 1)
